MUI_386_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\driver.obj \
    $(_OBJ_DIR)\i386\ioctrl.obj

MUI_IA64_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\driver.obj \
    $(_OBJ_DIR)\ia64\ioctrl.obj

MUI_AMD64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\driver.obj \
    $(_OBJ_DIR)\amd64\ioctrl.obj

MUI_ARM_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\driver.obj \
    $(_OBJ_DIR)\arm\ioctrl.obj

